GET localhost:8080/organizers

###

POST localhost:8080/registrations
Content-Type: application/json

{"productId": 801, "attendeeName": "Jesper de Jong"}

###

GET localhost:8080/registrations/5fb8d6fc-0a60-46b2-a8af-8fbb81559d4b

