GET localhost:8080/organizers

###

POST localhost:8080/registrations
Content-Type: application/json

{"productId": 801, "attendeeName": "Jesper de Jong"}

###

GET localhost:8080/registrations/dafb06c2-2151-43fc-b232-23d46fa1feca

