create table event (end_date date, id integer not null, organizer_id integer not null, start_date date, venue_id integer not null, name varchar(255) not null, primary key (id));
create table organizer (id integer not null, description varchar(255), name varchar(255) not null, primary key (id));
create table product (event_id integer not null, id integer not null, price numeric(38,2) not null, description varchar(255), name varchar(255) not null, primary key (id));
create table registration (id integer not null, product_id integer not null, attendee_name varchar(255), ticket_code varchar(255), primary key (id));
create table todo (completed boolean not null, id integer not null, user_id integer not null, title varchar(255) not null, primary key (id));
create table venue (id integer not null, city varchar(255), country varchar(255), name varchar(255) not null, street varchar(255), primary key (id));
alter table if exists event add constraint FKik6obgrxb8c6aakhf8fj7gs9h foreign key (organizer_id) references organizer;
alter table if exists event add constraint FKthgbmd6s6hp4l47kx1sh4cf9n foreign key (venue_id) references venue;
create table event (end_date date, id integer not null, organizer_id integer not null, start_date date, venue_id integer not null, name varchar(255) not null, primary key (id));
create table organizer (id integer not null, description varchar(255), name varchar(255) not null, primary key (id));
create table product (event_id integer not null, id integer not null, price numeric(38,2) not null, description varchar(255), name varchar(255) not null, primary key (id));
create table registration (id integer not null, product_id integer not null, attendee_name varchar(255), ticket_code varchar(255), primary key (id));
create table todo (completed boolean not null, id integer not null, user_id integer not null, title varchar(255) not null, primary key (id));
create table venue (id integer not null, city varchar(255), country varchar(255), name varchar(255) not null, street varchar(255), primary key (id));
alter table if exists event add constraint FKik6obgrxb8c6aakhf8fj7gs9h foreign key (organizer_id) references organizer;
alter table if exists event add constraint FKthgbmd6s6hp4l47kx1sh4cf9n foreign key (venue_id) references venue;
create table event (end_date date, id integer not null, organizer_id integer not null, start_date date, venue_id integer not null, name varchar(255) not null, primary key (id));
create table organizer (id integer not null, description varchar(255), name varchar(255) not null, primary key (id));
create table product (event_id integer not null, id integer not null, price numeric(38,2) not null, description varchar(255), name varchar(255) not null, primary key (id));
create table registration (id integer not null, product_id integer not null, attendee_name varchar(255), ticket_code varchar(255), primary key (id));
create table todo (completed boolean not null, id integer not null, user_id integer not null, title varchar(255) not null, primary key (id));
create table venue (id integer not null, city varchar(255), country varchar(255), name varchar(255) not null, street varchar(255), primary key (id));
alter table if exists event add constraint FKik6obgrxb8c6aakhf8fj7gs9h foreign key (organizer_id) references organizer;
alter table if exists event add constraint FKthgbmd6s6hp4l47kx1sh4cf9n foreign key (venue_id) references venue;
